In [2]:
import numpy as np

In [3]:
# 1. Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)

Array: [10 20 30 40 50]


In [4]:
# 2. Mean, Max, Min, Sum
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())
print("Sum:", arr.sum())

Mean: 30.0
Max: 50
Min: 10
Sum: 150


In [5]:
# 3. Two arrays and operations
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print("Addition:", arr_1 + arr_2)
print("Multiplication:", arr_1 * arr_2)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [6]:
# 4. Create a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("3x3 Matrix:\n", matrix)

3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
